### ISSUE TITLE
Can search results still be ordered by date?

### ISSUE THREAD

**Issue by Osndok** [Protuhj/myvideobuzz#102]
I'm really impressed to find a usable youtube client. I appreciate your work in making it v3 compatible!

I seem to recall a search by date (most recent first) being available, but I cannot find it. Is this something they removed in the v3 api?

I did see several mentions of bugs, like this:
https://code.google.com/p/gdata-issues/issues/detail?id=6506

**Comment by Protuhj** [comment]
You should be able to hit the '*' key on your remote, and bring up the options menu for search -- the option to sort by "most recent first" would be "Newest First".

**Comment by Osndok** [comment]
Thanks, somehow I missed that.

FYI, I am interested in (and intend to try and implement) these features, but have no idea yet on their feasibility or how long it would take me to accomplish:
(1) selecting an item from the recent/suggested list replaces the search field's content, and focuses on the 'search' button (instead of actually activating the search), and
(2) extract the sorting options into short-named (but separate) 'search' action links along the bottom of the search screen (e.g. 'Recent', 'Relevant', 'Popular', ...)

The first is mainly to allow the user to continue modifying the search string after the selection (one of the few features of the official youtube app that I like), while adding only one extra 'ok' press for someone to click through.

The second is because (using the old youtube app) I know that I would *always* be switching between 'recent' and 'popular', and the switch is presently a little to deeply buried. Well... also that there is no indication of the sorting mode from the search screen.

Thanks again!

**Comment by Protuhj** [comment]
> extract the sorting options into short-named (but separate) 'search' action links along the bottom of the search screen (e.g. 'Recent', 'Relevant', 'Popular', ...)  

I'm pretty sure this is impossible, based on the Roku API.

**Comment by Osndok** [comment]
Impossible? :(

I understand that it may not be easy, and might not be worth the time (e.g. to re-implement the standard search screen), but surly it is not "impossible"?

**Comment by Protuhj** [comment]
Ok, not impossible, but you'll find it pretty difficult, or tedious.

Brightscript isn't terribly flexible, but if you feel like trying to add
those buttons, I won't stop you!
