### ISSUE TITLE
youtube stream video crash

### ISSUE THREAD

**Issue by rangaramu** [Protuhj/myvideobuzz#110]
I am using roku3.
It appears that youtube live stream videos are crashing. please check

**Comment by Protuhj** [comment]
Can you point me to one that I can test with?

**Comment by rangaramu** [comment]
I tested 3 different ones....ll crashed.
https://www.youtube.com/watch?v=_YHAFJI7BKk

**Comment by Protuhj** [comment]
I'm watching BTV News right now -- can you make sure you're running Version 2.0 Build 4? (I just pushed a build 004 to the development branch).

**Comment by rangaramu** [comment]
I have version 2 and build 4. I just checked and it crashes on me.

**Comment by Protuhj** [comment]
Hmm.. are you familiar with PuTTY (or another telnet client)?  

If you Telnet to your Roku's IP address and port 8085, you can see any possible crash information.  

If not -- does the video at least try to play, and then fail to play? Or does the whole channel crash back to the home screen?

**Comment by rangaramu** [comment]
video try to load but the progress bar does not increase. it crashes the roku and roku restarts. I have roku3.

**Comment by Protuhj** [comment]
Weird.. have you tried the official YouTube channel?

**Comment by rangaramu** [comment]
youtube official does not support live streams

**Comment by Protuhj** [comment]
What Roku firmware does your Roku have? (I have 6.2 b3676)

**Comment by rangaramu** [comment]
i didnt know..now i can watch on youtube official. thanks

**Comment by Protuhj** [comment]
Sorry it doesn't work for you on Videobuzz.. it sounds like there has been some history of HLS (live streams) issues on Roku that causes hard-reboots.    

Generally, if your Roku is resetting, that isn't something than is caused directly by a channel.

**Comment by rangaramu** [comment]
Todays fix ver 2 build 5 fixed the bug. Thank you

**Comment by Protuhj** [comment]
Awesome, let me know if you have any more problems!
