### ISSUE TITLE
When set for auto updates, only show popup dialog if there is a new update

### ISSUE THREAD

**Issue by fritzwf** [Protuhj/myvideobuzz#111]
When a user has Videobuzz setup to do auto updating, the software currently pops up a dialog telling the user there is no new updates when the channel is started.  There is no need to pop up this dialog unless there are new updates since no popup implies that there are no new updates.

**Comment by Protuhj** [comment]
I'm adding a preference to be able to disable this message box.

**Comment by Protuhj** [comment]
Fix was added almost two years ago.
