### ISSUE TITLE
Youtube user id is not valid

### ISSUE THREAD

**Issue by hardhu** [Protuhj/myvideobuzz#112]
When setting the youtube user id as it is given in https://www.youtube.com/account_advanced, you get an error message saying that the user id is not a valid youyube user id.

**Comment by Protuhj** [comment]
Make sure you entered in the ID EXACTLY as it is shown on that page (letter case matters!)  
Also, make sure you're running the latest build (Build 006) of the channel.

**Comment by hardhu** [comment]
Ok, I found the culprit: what I believed to be a lowercase l was instead an uppercase i.
Sorry for the wrong report, I close the issue

**Comment by Protuhj** [comment]
Sorry that this is pretty clunky, I blame Google!
