### ISSUE TITLE
Since release 2.1.0 I have been getting random "Unknown Playback Error"

### ISSUE THREAD

**Issue by fritzwf** [Protuhj/myvideobuzz#119]
Since I installed release 2.1.0 I have been getting random **Unknown Playback Error** with **Video Playback Failed** message popup dialog.  These videos were not music, they were just regular videos.

**Comment by Protuhj** [comment]
YouTube seems to have changed their encoding scheme to something that the Roku can't play in 720p. Until I can find a possible solution, the only workaround is to:

Go into Settings (on the main page of the channel) -> General Settings -> Video Quality -> Force to Lowest.

I know this isn't ideal, but it's the only solution I currently know about.

**Comment by snowe2010** [comment]
any solution for this yet?

**Comment by Protuhj** [comment]
Sorry for taking a few days to respond.. but are you running the latest development version? 
Version 2.1.023. As far as I can tell, this hasn't been a problem in a while, as they have pushed firmware changes that have seemed to fix it.

**Comment by snowe2010** [comment]
ok after restarting the app it seems like it wanted to update and I was able to update to .023. Thanks and sorry for the trouble!

**Comment by Protuhj** [comment]
No worries.. I'm due to push a new release. I had been waiting to see if the firmware updates would fix the playback issues, and haven't made a new release since then.

**Comment by Protuhj** [comment]
Should be fixed in v2.2.0
