### ISSUE TITLE
Add support for multiple accounts, and switching between them.

### ISSUE THREAD

**Issue by Protuhj** [Protuhj/myvideobuzz#121]
It has been requested that support for multiple YouTube accounts be added to the channel, and of course, some way to switch between them.

**Comment by fritzwf** [comment]
How about adding multiple accounts, and just concatenate the subscriptions instead of switching between them.  That should be fairly easy to do with the existing code base.

**Comment by Protuhj** [comment]
That would be doable, but I have to imagine people have different subscriptions for distinct reasons.

**Comment by Protuhj** [comment]
Closing due to project archival.
