### ISSUE TITLE
Access to my 'Liked videos' playlist

### ISSUE THREAD

**Issue by gitguys** [Protuhj/myvideobuzz#122]
Is there any way to add access to my '**Liked videos**' playlist? I've made it a public playlist and not sure why it's not showing up with MyVideoBuzz anywhere.  It would be great to have since the only way I can add videos to any kind of playlist through the official YouTube Roku app is by liking them and I want to easily pull up those liked videos with your app as well.  Thank you.

**Comment by Protuhj** [comment]
A workaround: If you create a playlist, and make it public, you can add videos you want to watch later to that playlist and they'll show up.

After a while, the 'Liked' playlist becomes huge (Mine has over 4,000 videos right now).  

I've also got an Android app working locally (for personal use) that I can share if you're not scared to beta test it.

**Comment by gitguys** [comment]
Thank you for the quick response! Are you saying that if I create a public playlist I can add videos to it from the official YouTube Roku app?  The only option I see is just being able to 'Like" videos from that interface.  I should probably break down what I'm trying to accomplish.

1) I most often use the official YouTube Roku app to watch videos for various reasons.

2) On occasion there's videos I want to skip around on, but the official app is horribly slow for that and even gets stuck on 'Loading...' fairly often. On the other hand, your MVB app is vastly faster for skipping through the video timelines & I choose to use it on those problem videos.

3) I want to view the problems videos I want to skip through with MVB, however I then have to spend time searching for the video with MVB since the official app's 'History' isn't mutually shared with MVB.

4) I would prefer to access the 'Liked' playlist from MVB since it's the _only_ playlist that videos can be added from the official YouTube Roku app.

**Comment by Protuhj** [comment]
I'll take a look when I get home and see if adding the Liked Videos list is possible without having to authenticate.

**Comment by gitguys** [comment]
Thank you! If it helps, I tested it myself.  On my laptop browser, I opened my YouTube 'Liked playlist', clicked the 'share' button and copied the url.  I then logged out of my account, pasted the url and was able to open that url to my 'Liked playlist' just fine.

**Comment by gitguys** [comment]
Hi Protuhj, does it look like this is something that may be implemented?  Is so, do you have a rough timeframe I should look for the update?  Thank you!

**Comment by Protuhj** [comment]
Update your channel from the latest development release, it should be available now.

**Comment by Protuhj** [comment]
Were you able to test this out?

**Comment by gitguys** [comment]
Yes, it works perfect!  Thank you very much for implementing the feature!  Now when I'm using the official YouTube app and want to jump through time on it, I just "like" it and open your app to fly through the timeline near-instantly.  Perfect for long speeches, events, etc. that normally cripple the official Youtube Roku app.
