### ISSUE TITLE
Playlist does not load

### ISSUE THREAD

**Issue by pnut1** [Protuhj/myvideobuzz#126]
When I try to access my playlist, it just shows loading but never loads. This problem started about a week or so back. The playlists are not restricted.

**Comment by Protuhj** [comment]
If you go to YouTube on a computer, does the playlist you're trying to view have deleted videos in it? (There's an issue #125 that I haven't pushed the fix for yet) 

If the playlist doesn't have any deleted videos, can you send me the playlist's link?

**Comment by Protuhj** [comment]
Closing due to lack of response.
