### ISSUE TITLE
Roku ending support for our legacy BrightScript visual screen components

### ISSUE THREAD

**Issue by fritzwf** [Protuhj/myvideobuzz#130]
Not sure if this effects Videobuzz, but I thought I'd post it here.

Dear developer:

In order to modernize the Roku experience, we will be ending support for our legacy BrightScript visual screen components. These components will be removed from Roku OS on January 1, 2019. Developers who wish to remain on the Roku platform must update their channel UI using Roku SceneGraph ("RSG") or Direct Publisher.

There is a two-year roadmap for developers to transition to RSG. Below are key dates:

Effective immediately: No new features will be added to our legacy SDK visual screens
July 1, 2017: All new channels must use RSG or Direct Publisher
January 1, 2018: All channel updates must use RSG or Direct Publisher
January 1, 2019: Legacy visual screen components will be removed from Roku OS

**Comment by Protuhj** [comment]
Yea, I've seen this, and I'm not totally happy with it.  

I've looked into doing some porting already, but porting from pure BrightScript to SceneGraph isn't an easy task. 

Thanks for creating the issue!

**Comment by fritzwf** [comment]
I had a suspicion that converting Videobuzz to the new screen components would be a big job.  Hopefully it's not a complete rewrite.

**Comment by Protuhj** [comment]
Closing due to project archival.
