### ISSUE TITLE
Add YouTube "live" search filter (maybe even a live-stream section?)

### ISSUE THREAD

**Issue by mizzmona** [Protuhj/myvideobuzz#131]
The following URL parameter filters for "live" streams:
sp=EgJAAQ%253D%253D

Example "fox news live" search for live streams only:
https://www.youtube.com/results?q=fox+news+live&sp=EgJAAQ%253D%253D

HTH.

Love the Buzz! Thanks.
-mzm

**Comment by Protuhj** [comment]
Cool -- I'll look at adding that. Thanks!

**Comment by Protuhj** [comment]
Relevant V3 API field: eventType with a value of "live".

**Comment by mizzmona** [comment]
Just realized that's a double encoded string... how odd.

Anyway, it also appears to work fine encoded normally:
sp=EgJAAQ%3D%3D

Have fun.

-M

**Comment by Protuhj** [comment]
Confirmed adding "eventType" = "live" will work, just need to add the plumbing to allow the user to choose to search for them.

**Comment by Protuhj** [comment]
This feature has been added.
