### ISSUE TITLE
Adding reddit view-by-domain support

### ISSUE THREAD

**Issue by youvegottabecrazy** [Protuhj/myvideobuzz#155]
The reddit site-wide by-domain view:
 `https://www.reddit.com/domain/youtube.com/`

Is the same structure, uses the same feeds, and accepts the same filters as the by-subreddit view:
  `https://www.reddit.com/r/VideoBuzz`

Subreddits cannot contain a period (.). Domains all contain a period.

VB's existing by-subreddit functionality can be made to handle domains by 1) checking the entry for a period. 2) If it contains a period, use the /domain/ URL instead of the /r/ URL.

Domains VB will support: youtu.be. youtube.com, m.youtube.com gfycat.com, streamable.com, liveleak.com vine.co 

(Included for completeness.) Some domains that VB once supported no longer work with VB. This may be temporarily broken, or permanently broken, I don't know. I checked these & determined they do not currently work with VB: drive.google.com docs.google.com vidzi.tv  

Pull request ---> #154

**Comment by Protuhj** [comment]
Closing now that this has been merged to master.
