### ISSUE TITLE
Some non-existing gfycat videos cause VB crash, requiring restart

### ISSUE THREAD

**Issue by youvegottabecrazy** [Protuhj/myvideobuzz#156]
getGfycatMP4Url() relies on (json <> invalid) to determine a video doesn't exist. Gfycat is returning valid json for these deleted videos, so VB attempts to play them, causing the app to crash.

json returned: 
```
<Component: roAssociativeArray> =
{
    error: "gifs does not exist."
}
```

Changing the check to:

`if (json <> invalid and not json.doesExist("error")) then
`

fixes the problem. 

I'll submit a pull request when I have time, unless you incorporate this change on your own before then.

**Comment by Protuhj** [comment]
Can you submit the broken link to /r/videobuzztest? 

I'm planning on merging your changes tonight, after I do some basic tests of course.

**Comment by youvegottabecrazy** [comment]
Sorry, just saw this now. If you still need it, I'll try to track one down. 

(Unrelated: I just added support for imgur gifv files.)

**Comment by Protuhj** [comment]
If you've got stuff you'd like to add, just make an issue for it, and I'll get it merged in!

Thanks for your contributions!

**Comment by Protuhj** [comment]
Closing due to project archival.
