### ISSUE TITLE
Add support for imgur-hosted gifv files

### ISSUE THREAD

**Issue by youvegottabecrazy** [Protuhj/myvideobuzz#159]
All imgur filename.gifv files also have a filename.mp4 version available. This simplifies things. 

Pull request -> #158

Test link submitted to /r/videobuzztest

======================================

I was going to do a separate pull request for another enhancement, but it looks like github pulled it into this one.  (They were separate commits, and I did the second commit after doing the first pull request, but apparently that does not matter. TIL that's how git works b/c pull requests are branch merges.) 

It's in there & I have no idea how to get it out of there, so I suppose I should tell you what that other change is all about. Sorry about the mess. 

It's just 2 lines. It adds support for user-created multis. 

The thing VB calls multis, sub1+sub2+sub3 aren't really multis. Multis are user-created groups of reddits that go by the url /user/[username]/m/[multi-name]

A bunch of multis are listed here: https://www.reddit.com/r/multihub/

For example, here's a multi of a dozen subs: https://www.reddit.com/user/bombmars/m/gawk/

(see the sub list in the sidebar)

This change allows a VB-user to add "bombmars/m/gawk" to their subreddit list & have it show up like any other subreddit.

**Comment by Protuhj** [comment]
This has been added in build 007.
