### ISSUE TITLE
Some videos cause roku to lose sound. Roku needs to be rebooted to get it back.

### ISSUE THREAD

**Issue by youvegottabecrazy** [Protuhj/myvideobuzz#160]
Example video submitted to vbtest

https://www.reddit.com/r/VideoBuzzTest/comments/88haj0/playing_this_video_will_cause_your_roku_to_lose/

Nothing in the error console.

I've seen this happen on youtube videos, too.

I'm using a Roku 3.

I don't know that anything can be done to fix this--probably a roku problem--but I wanted to document it.

**Comment by Protuhj** [comment]
I think this is a Roku 3 problem since my Roku 2 didn't lose sound. 

It seems like Roku 3 has some issues with audio/video playback as of the current firmware.

**Comment by Protuhj** [comment]
Closing due to project archival.
