### ISSUE TITLE
Vevo music videos

### ISSUE THREAD

**Issue by cactus2003** [Protuhj/myvideobuzz#21]
I imagine this is pretty low priority, seeing as there is a Vevo Channel for Roku already.  I'm not going to dispute that, however it would be nice if the music videos from Vevo worked.  Like if I want to show my friend a music video or something, I can just use VideoBuzz instead of wandering around the clunky interface of the official Vevo channel.

Not only that, but there are actually quite a lot of music videos that don't work that aren't waving the Vevo flag around.

Just a slight inconvenience, but it would be nice if they worked.  

P.S. By the way, Loving the new update!  I especially look forward to playing around with the reddit feature!

P.P.S. Didn't realize this wasn't the "official" version (as in the version from utmostsolutions), sorry if this is the wrong place to post this!

**Comment by Protuhj** [comment]
Closing this bug, as it appears this has been functional since I pushed the update.
