### ISSUE TITLE
Unknown Playback Error on Google Drive videos.

### ISSUE THREAD

**Issue by cactus2003** [Protuhj/myvideobuzz#62]
I've been testing out the new Google Drive support and so far, I've watched two videos.  During both videos, the video suddenly quit and presented a dialogue that said "Unknown Playback Error" or something along the lines of that.  The first time, it quit 45 minutes into a 1 hour and 30 minute video.  The second time, it quit 1 hour and 2 minutes into a 2 hour video.

Both times, I pressed "OK" and resumed the video only for it to play right where it left off flawlessly.

It seems harmless, yet annoying, so I figured you would want to take a look into this.

**Comment by Protuhj** [comment]
Closing due to project archival.
