### ISSUE TITLE
Age-Restricted YouTube videos don't work.

### ISSUE THREAD

**Issue by corncresident** [Protuhj/myvideobuzz#98]
Doesn't matter what kind they are, music, trailer, or otherwise.

Examples: 

https://www.youtube.com/watch?v=1EROmqidZQc
https://www.youtube.com/watch?v=kP8O-MOqmcw
https://www.youtube.com/watch?v=nje6dcArZrI
https://www.youtube.com/watch?v=UMyoCr2MnpM
https://www.youtube.com/watch?v=5_yOGBzBTdc

**Comment by Protuhj** [comment]
Looking into it now.

**Comment by Protuhj** [comment]
Verified that all videos you posted now work.

**Comment by corncresident** [comment]
Awesome, appreciate the quick response.
